# Convert the ECLE spreadsheet data to the OTTER format

In [1]:
import pandas as pd
import numpy as np
import json as jj
from otter.util import bibcode_to_hrn
from otter import Otter

radio = pd.read_csv('ecle-radio-data.csv')
radio = radio[~pd.isna(radio.flux)]
radio = radio[radio.use_this] # this will reduce redundancy

ir = pd.read_csv('data/wise-photometry.csv')

meta = pd.read_csv('ecle-meta-data.csv')

data = pd.merge(meta, radio, on='name')

data

,name,ra,ra_unit,dec,dec_unit,coord_ref,discovery_date,discovery_date_format,discovery_date_ref,redshift,...,filter_eff,filter_eff_units,flux,flux_err,flux_unit,upperlimit,reducer,source,use_this,comments
0,2019qiz,04:46:37.880,hour,-10:13:34.90,degree,2019TNSTR1857....1F,2458745.9998032,JD,2019TNSTR1857....1F,0.0151,...,3.000,GHz,0.354325,0.0,mJy,True,VLASS 1.1,VLASS 1.1,True,NaN
1,2019qiz,04:46:37.880,hour,-10:13:34.90,degree,2019TNSTR1857....1F,2458745.9998032,JD,2019TNSTR1857....1F,0.0151,...,3.000,GHz,0.503589,0.0,mJy,True,VLASS 3.1,VLASS 3.1,True,NaN
2,2019qiz,04:46:37.880,hour,-10:13:34.90,degree,2019TNSTR1857....1F,2458745.9998032,JD,2019TNSTR1857....1F,0.0151,...,3.000,GHz,0.540518,0.0,mJy,True,VLASS 2.1,VLASS 2.1,True,NaN
3,SDSS_J0748,07:48:20.6668,hour,+47:12:14.2648,degree,2024arXiv240216951C,2004-02-20,iso,2024MNRAS.528.7076C,0.0616,...,4.999,GHz,130.300000,13.5,uJy,False,Kate with pwkit,15B-247,True,NaN
4,SDSS_J0748,07:48:20.6668,hour,+47:12:14.2648,degree,2024arXiv240216951C,2004-02-20,iso,2024MNRAS.528.7076C,0.0616,...,7.099,GHz,95.400000,9.2,uJy,False,Kate with pwkit,15B-247,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,AT2021acak,10:34:47.99,hour,+15:29:22.42,degree,2023RAA....23b5012L,2459510.12,JD,2021TNSTR3613....1T,0.1360,...,3.000,GHz,0.320902,0.0,mJy,True,VLASS 1.1,VLASS 1.1,True,NaN
118,AT2021acak,10:34:47.99,hour,+15:29:22.42,degree,2023RAA....23b5012L,2459510.12,JD,2021TNSTR3613....1T,0.1360,...,3.000,GHz,0.376332,0.0,mJy,True,VLASS 2.1,VLASS 2.1,True,NaN
119,AT2021acak,10:34:47.99,hour,+15:29:22.42,degree,2023RAA....23b5012L,2459510.12,JD,2021TNSTR3613....1T,0.1360,...,3.000,GHz,0.380926,0.0,mJy,True,VLASS 3.1,VLASS 3.1,True,NaN
120,AT2018dyk,15:33:08.015,hour,+44:32:08.20,degree,2018TNSTR.987....1F,2458269.81,JD,2018TNSTR.987....1F,0.0370,...,3.000,GHz,0.533881,0.0,mJy,True,VLASS 2.2,VLASS 2.2,True,NaN
121,AT2018dyk,15:33:08.015,hour,+44:32:08.20,degree,2018TNSTR.987....1F,2458269.81,JD,2018TNSTR.987....1F,0.0370,...,3.000,GHz,0.367570,0.0,mJy,True,VLASS 1.2,VLASS 1.2,True,NaN

In [2]:
radio

,name,day,date_mjd,array_config,filter,filter_eff,filter_eff_units,flux,flux_err,flux_unit,upperlimit,reducer,source,use_this,comments
0,2019qiz,2018-01-10 5:44:01,58128.23890,B,S,3.0,GHz,0.354325,0.000000,mJy,True,VLASS 1.1,VLASS 1.1,True,NaN
1,2019qiz,2023-03-25 0:11:29,60028.00797,B,S,3.0,GHz,0.503589,0.000000,mJy,True,VLASS 3.1,VLASS 3.1,True,NaN
2,2019qiz,2020-10-20 10:14:16,59142.42657,B,S,3.0,GHz,0.540518,0.000000,mJy,True,VLASS 2.1,VLASS 2.1,True,NaN
3,AT2017gge,2017-11-24 17:51:31,58081.74411,B,S,3.0,GHz,0.335485,0.000000,mJy,True,VLASS 1.1,VLASS 1.1,True,NaN
4,AT2017gge,2023-03-01 9:40:17,60004.40297,B,S,3.0,GHz,0.459018,0.124565,mJy,False,VLASS 3.1,VLASS 3.1,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,SDSS_J1715,2020-08-03 6:23:11,59064.26610,B,S,3.0,GHz,0.499633,0.000000,mJy,True,VLASS 2.1,VLASS 2.1,True,NaN
148,SDSS_J1715,2023-02-09 15:50:28,59984.66004,B,S,3.0,GHz,0.346932,0.000000,mJy,True,VLASS 3.1,VLASS 3.1,True,NaN
149,SDSS_J2220,2017-11-28 2:25:10,58085.10082,B,S,3.0,GHz,0.428375,0.000000,mJy,True,VLASS 1.1,VLASS 1.1,True,NaN
150,SDSS_J2220,2020-07-10 12:02:52,59040.50199,B,S,3.0,GHz,0.524493,0.000000,mJy,True,VLASS 2.1,VLASS 2.1,True,NaN
151,SDSS_J2220,2023-01-15 23:17:43,59959.97064,B,S,3.0,GHz,0.509408,0.000000,mJy,True,VLASS 3.1,VLASS 3.1,True,NaN

In [3]:
db = Otter('ecle-otter')

db.generate_summary_table()

/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)

,name,alias,ra,dec,refs,discovery_date,hasPhot,hasSpec,json_path,z
0,2019pqt,"[2019pqt, Gaia19dya, MAXI J1807+132]",272d01m53.235s,13d15m05.4s,"[2017ATel10216....1K, 2011ApJ...737..103S, 201...",2017-03-27 00:00:00.000,True,False,/home/nfranz/radio-ecle/ecle-otter/MAXI-J1807+...,NaN
1,SDSSJ1323,[SDSSJ1323],200d55m29.55s,48d27m01.26s,"[2017ApJ...838..149A, 2016A&A...594A..13P, 200...",2003-12-02 00:00:00.000,True,False,/home/nfranz/radio-ecle/ecle-otter/SDSSJ1323.json,0.08754
2,AT2016ezh,"[AT2016ezh, CSS160902:015805-005222, SN2016ezh...",29d31m15s,-0d52m22s,"[2017arXiv170307816B, 2017ApJ...843..106B, 201...",2016-08-26 15:07:12.000,True,False,/home/nfranz/radio-ecle/ecle-otter/AT2016ezh.json,0.08
3,2022exr,"[ZTF22aadgefj, 2022exr, Gaia22cgf, ATLAS22jix,...",262d27m37.66464s,25d50m31.79148s,"[2022TNSCR1202....1H, 2024MNRAS.527.2452M, 202...",59658.61201,True,False,/home/nfranz/radio-ecle/ecle-otter/AT2022exr.json,0.0955
4,2021crk,"[PS21cpw, ATLAS21hdc, 2021crk, ZTF21aakfqwq, A...",176d16m43.61088s,18d32m25.32408s,"[2022ApJ...925...67L, 2024MNRAS.527.2452M, 202...",59252.48956019676,True,False,/home/nfranz/radio-ecle/ecle-otter/AT2021crk.json,0.155
...,...,...,...,...,...,...,...,...,...,...
163,RBS 1032,[RBS 1032],176d51m42s,49d42m59s,"[2017ApJ...838..149A, 2016A&A...594A..13P, 201...",1990-11-05 00:00:00.000,True,False,/home/nfranz/radio-ecle/ecle-otter/RBS-1032.json,0.026
164,2020mbq,"[2020mbq, PS20grv, ATLAS20pfz, ZTF20abefeab, A...",235d03m48.9204s,25d00m04.8276s,"[2023ApJ...942....9H, 2024MNRAS.527.2452M, 202...",59009.25196760417,True,False,/home/nfranz/radio-ecle/ecle-otter/AT2020mbq.json,0.093
165,2020ocn,"[ZTF18aakelin, 2020ocn, AT2020ocn]",208d28m27.0160428s,53d59m49.7309352s,"[2023ApJ...942....9H, 2024MNRAS.527.2452M, 202...",58968.305,True,False,/home/nfranz/radio-ecle/ecle-otter/AT2020ocn.json,0.07
166,2021ehb,"[ZTF21aanxhjv, ATLAS21jdy, 2021ehb, AT2021ehb]",46d56m57.39972s,40d18m40.44816s,"[2022ApJ...937....8Y, 2024MNRAS.527.2452M, 202...",59274.143090300924,True,False,/home/nfranz/radio-ecle/ecle-otter/AT2021ehb.json,0.017
167,J133737,[J133737],204d24m16.95s,20d23m51.7s,"[2018arXiv180205105W, 2016A&A...594A..13P, 201...",2009-04-12 00:00:00.000,True,False,/home/nfranz/radio-ecle/ecle-otter/J133737.json,0.0725

In [13]:
ecle_jsons = []

for name, ecle in data.groupby('name'):
    
    json = {}
    ecle = ecle.reset_index()
    
    # name first
    json['name'] = dict(
        default_name = name,
        alias = [dict(
            value = name,
            reference = [ecle.coord_ref[0]]
        )]
    )
    
    # coordinates
    json['coordinate'] = [dict(
        ra = ecle.ra[0],
        dec = ecle.dec[0],
        ra_units = ecle.ra_unit[0],
        dec_units = ecle.dec_unit[0],
        reference = [ecle.coord_ref[0]],
        coordinate_type = 'equitorial'
    )]
    
    # redshift
    json['distance'] = [dict(
        value = ecle.redshift[0],
        reference = [ecle.redshift_ref[0]],
        compute = False,
        distance_type = 'redshift'
    )]
    
    # classification
    if ecle.classification[0] in {'TDE', 'AGN'}:
        objclass = ecle.classification[0]
        objconf = 1
    else:
        # this is likely an AGN but with a low confidence
        objclass = 'AGN' 
        objconf = 0.1
        
    json['classification'] = [
        dict(
            object_class = 'ECLE',
            confidence = 1, # we know this is at least an ECLE
            reference = [ecle.classification_ref[0]]
        ),
        dict(
            object_class = objclass,
            confidence = objconf,
            reference = [ecle.classification_ref[0]]
        )
    ]
    
    # discovery date
    # print(ecle)
    if not np.any(pd.isna(ecle.discovery_date)):
        json['date_reference'] = [
            dict(
                value = ecle.discovery_date.tolist()[0].strip(),
                date_format = ecle.discovery_date_format.tolist()[0].lower(),
                reference = ecle.discovery_date_ref.tolist()[0],
                computed = False,
                date_type = 'discovery'
            )
        ]
    
    # now the radio photometry
    phot_sources = []
    json['photometry'] = []
    for src, phot in ecle.groupby('source'):
        
        if src not in phot_sources:
            phot_sources.append(src)
            
        if len(np.unique(phot.flux_unit)) == 1:
            # print(type(phot.flux_unit.values))
            raw_units = phot.flux_unit.tolist()[0]
        else:
            raw_units = phot.flux_unit.values
            
        json_phot = dict(
            reference = src, # since this is unpublished data we don't need it to be a bibcode
            raw = phot.flux.tolist(),
            raw_err = phot.flux_err.tolist(),
            raw_units = raw_units,
            date = phot.date_mjd.tolist(),
            date_format = 'mjd',
            upperlimit = phot.upperlimit.tolist(),
            telescope = 'VLA',
            filter_key = phot['filter'].tolist(),
            obs_type = 'radio',
            reducer = phot.reducer.tolist()
        )
        
        json['photometry'].append(json_phot)
        
    # now the IR photometry
    src = 'WISE'
    phot_ir = ir[ir.name == name]        
    
    if src not in phot_sources:
        phot_sources.append(src)
            
    if len(np.unique(phot_ir.flux_unit)) == 1:
        # print(type(phot.flux_unit.values))
        raw_units = phot_ir.flux_unit.tolist()[0]
    else:
        raw_units = phot_ir.flux_unit.tolist()
            
    json_phot = dict(
        reference = src, # since this is unpublished data we don't need it to be a bibcode
        raw = phot_ir.flux.tolist(),
        raw_err = phot_ir.flux_err.tolist(),
        raw_units = raw_units,
        date = phot_ir.date_mjd.tolist(),
        date_format = 'mjd',
        upperlimit = phot_ir.upperlimit.tolist(),
        telescope = 'WISE',
        filter_key = phot_ir['filter'].tolist(),
        obs_type = 'uvoir'
    )

    json['photometry'].append(json_phot)
    
    # filter alias
    # radio filters first
    filter_keys1 = ['filter', 'filter_eff', 'filter_eff_units']
    filter_keys2 = ['filter', 'filter_eff', 'filter_eff_unit'] 
    filter_map_radio = ecle[filter_keys1].drop_duplicates().set_index('filter')#.to_dict(orient='index')
    try:
        filter_map_radio = filter_map_radio.to_dict(orient='index')
    except:
        print(filter_map)
        print(name)
        raise Exception
    json['filter_alias'] = [dict(
        filter_key = filt,
        freq_eff = val['filter_eff'],
        freq_units = val['filter_eff_units']
    ) for filt, val in filter_map_radio.items() ]
    
    # the IR filters
    filter_map_ir = phot_ir[filter_keys2].drop_duplicates().set_index('filter').to_dict(orient='index')
    json['filter_alias'] += [dict(
        filter_key = filt,
        wave_eff = val['filter_eff'],
        wave_units = val['filter_eff_unit']
    ) for filt, val in filter_map_ir.items() ]
    
    print(json['filter_alias'])
    
    # reference alias
    json['reference_alias'] = [
        dict(
            name = ecle.coord_ref[0],
            human_readable_name = bibcode_to_hrn(ecle.coord_ref[0])
        )
    ] + [dict(name=val,human_readable_name=val) for val in phot_sources]
    
    curr_refs = {v['name'] for v in json['reference_alias']}
    if ecle.redshift_ref[0] not in curr_refs:
        json['reference_alias'].append(dict(
            name = ecle.redshift_ref[0],
            human_readable_name = bibcode_to_hrn(ecle.redshift_ref[0])
        ))
        
    curr_refs = {v['name'] for v in json['reference_alias']}
    if ecle.classification_ref[0] not in curr_refs:
        json['reference_alias'].append(dict(
            name = ecle.classification_ref[0],
            human_readable_name = bibcode_to_hrn(ecle.classification_ref[0])
        ))
        
    #     print(jj.dumps(json, indent=4))
    #     print('#############################################################################################')
    #     print()
    #     print()
    
    ecle_jsons.append(json)

# db.save(ecle_jsons, testing=False)

[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'L1', 'freq_eff': 1.255, 'freq_units': 'GHz'}, {'filter_key': 'L2', 'freq_eff': 1.644, 'freq_units': 'GHz'}, {'filter_key': 'S (IF 1-8)', 'freq_eff': 2.599, 'freq_units': 'GHz'}, {'filter_key': 'S (IF 9-16)', 'freq_eff': 3.399, 'freq_units': 'GHz'}, {'filter_key': 'X (IF 1-8)', 'freq_eff': 8.549, 'freq_units': 'GHz'}, {'filter_key': 'X (IF 9-16)', 'freq_eff': 10.999, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'L1', 'freq_eff': 1.255, 'freq_units': 'GHz'}, {'filter_key': 'L2', 'freq_eff': 1.644, 'freq_units': 'GHz'}, {'filter_key': 'S (IF 1-8)', 'freq_eff': 2.599, 'freq_units': 'GHz'}, {'filter_key': 'S (IF 9-16)', 'freq_eff': 3.399, 'freq_units': 'GHz'}, {'filter_key': 'X (IF 1-8)', 'freq_eff': 8.549, 'freq_units': 'GHz'}, {'filter_key': 'X (IF 9-16)', 'freq_eff': 10.999, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'L1', 'freq_eff': 1.255, 'freq_units': 'GHz'}, {'filter_key': 'L2', 'freq_eff': 1.644, 'freq_units': 'GHz'}, {'filter_key': 'C (all_3bit)', 'freq_eff': 5.957, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'L1', 'freq_eff': 1.3, 'freq_units': 'GHz'}, {'filter_key': 'L2', 'freq_eff': 1.775, 'freq_units': 'GHz'}, {'filter_key': 'S (IF 1-8)', 'freq_eff': 2.627, 'freq_units': 'GHz'}, {'filter_key': 'S (IF 9-16)', 'freq_eff': 3.523, 'freq_units': 'GHz'}, {'filter_key': 'X (IF 1-8)', 'freq_eff': 8.549, 'freq_units': 'GHz'}, {'filter_key': 'X (IF 9-16)', 'freq_eff': 10.999, 'freq_units': 'GHz'}, {'filter_key': 'C1', 'freq_eff': 5.0, 'freq_units': 'GHz'}, {'filter_key': 'C2', 'freq_eff': 7.0, 'freq_units': 'GHz'}, {'filter_key': 'X1', 'freq_eff': 9.12653, 'freq_units': 'GHz'}, {'filter_key': 'S2', 'freq_eff': 3.49882, 'freq_units': 'GHz'}, {'filter_key': 'X2', 'freq_eff': 10.998433, 'freq_units': 'GHz'}, {'filter_key': 'S1', 'freq_eff': 2.498871, 'freq_units': 'GHz'}, {'filter_key': 'L', 'freq_eff': 1.55, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'C (IF 1-8)', 'freq_eff': 4.999, 'freq_units': 'GHz'}, {'filter_key': 'C (IF 9-16)', 'freq_eff': 7.099, 'freq_units': 'GHz'}, {'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]
[{'filter_key': 'S', 'freq_eff': 3.0, 'freq_units': 'GHz'}, {'filter_key': 'w1', 'wave_eff': 3.4, 'wave_units': 'um'}, {'filter_key': 'w2', 'wave_eff': 4.6, 'wave_units': 'um'}, {'filter_key': 'w3', 'wave_eff': 12.0, 'wave_units': 'um'}, {'filter_key': 'w4', 'wave_eff': 22.0, 'wave_units': 'um'}]

In [5]:
qiz = meta[meta.name == '2019qiz']

from astropy.coordinates import SkyCoord
coord = SkyCoord(qiz.ra, qiz.dec, unit=(qiz.ra_unit.values[0], qiz.dec_unit.values[0]))

db.cone_search(coord)

[Transient(
 	Name: 2019qiz,
 	Keys: dict_keys(['reference_alias', 'classification', 'name', 'date_reference', 'filter_alias', 'photometry', 'coordinate', 'distance', 'schema_version'])
 )]

In [6]:
coord2 = SkyCoord(71.657837, -10.226355, unit='deg')

In [7]:
coord.separation(coord2)

In [8]:
coord3 = SkyCoord("4:46:37.99", "-10:13:31.5", unit=("hour", "deg"))

In [9]:
coord3.separation(coord)

In [10]:
coord3.separation(coord2)

In [12]:
db.get_phot(names='2019qiz', obs_type='uvoir')

/home/nfranz/astro-otter/otter/src/otter/io/transient.py:515: UserWarning: Unable to apply the source mapping because '2020MNRAS.499..482N,2021ApJ...908....4V'
  warnings.warn(f"Unable to apply the source mapping because {exc}")
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))
/home/nfranz/.local/lib/anaconda3/lib/python3.11/site-packages/astropy/units/function/logarithmic.py:67: RuntimeWarning: invalid value encountered in log10
  return dex.to(self._function_unit, np.log10(x))

<Table length=1389>
  name    converted_flux   ... telescope
  str7       float64       ...    str4
------- ------------------ ... ---------
2019qiz                 -- ...        --
2019qiz                 -- ...        --
2019qiz 21.542078709283146 ...        --
2019qiz                 -- ...        --
2019qiz 22.363348675763692 ...        --
2019qiz 21.518149587785636 ...        --
2019qiz 21.488947717020054 ...        --
2019qiz  21.90106488891175 ...        --
2019qiz                 -- ...        --
    ...                ... ...       ...
2019qiz             10.714 ...      WISE
2019qiz             10.989 ...      WISE
2019qiz              7.783 ...      WISE
2019qiz              7.304 ...      WISE
2019qiz              7.695 ...      WISE
2019qiz              7.411 ...      WISE
2019qiz              6.611 ...      WISE
2019qiz               7.03 ...      WISE
2019qiz              7.526 ...      WISE
2019qiz              7.945 ...      WISE